/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = agent.Client.OpenAPIDateConverter;

namespace agent.Model
{
    /// <summary>
    /// AgentListAgentsRequest
    /// </summary>
    [DataContract(Name = "Agent_ListAgents_request")]
    public partial class AgentListAgentsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentListAgentsRequest" /> class.
        /// </summary>
        /// <param name="pageToken">pageToken.</param>
        /// <param name="sorts">sorts.</param>
        /// <param name="filtersMask">filtersMask.</param>
        /// <param name="filters">filters.</param>
        public AgentListAgentsRequest(string pageToken = default(string), List<ListRequestSort> sorts = default(List<ListRequestSort>), string filtersMask = default(string), ListRequestFilters filters = default(ListRequestFilters))
        {
            this.PageToken = pageToken;
            this.Sorts = sorts;
            this.FiltersMask = filtersMask;
            this.Filters = filters;
        }

        /// <summary>
        /// Gets or Sets PageToken
        /// </summary>
        [DataMember(Name = "pageToken", EmitDefaultValue = false)]
        public string PageToken { get; set; }

        /// <summary>
        /// Gets or Sets Sorts
        /// </summary>
        [DataMember(Name = "sorts", EmitDefaultValue = false)]
        public List<ListRequestSort> Sorts { get; set; }

        /// <summary>
        /// Gets or Sets FiltersMask
        /// </summary>
        [DataMember(Name = "filtersMask", EmitDefaultValue = false)]
        public string FiltersMask { get; set; }

        /// <summary>
        /// Gets or Sets Filters
        /// </summary>
        [DataMember(Name = "filters", EmitDefaultValue = false)]
        public ListRequestFilters Filters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AgentListAgentsRequest {\n");
            sb.Append("  PageToken: ").Append(PageToken).Append("\n");
            sb.Append("  Sorts: ").Append(Sorts).Append("\n");
            sb.Append("  FiltersMask: ").Append(FiltersMask).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
