/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = agent.Client.OpenAPIDateConverter;

namespace agent.Model
{
    /// <summary>
    /// ListRequestSort
    /// </summary>
    [DataContract(Name = "ListRequestSort")]
    public partial class ListRequestSort : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        [DataMember(Name = "field", EmitDefaultValue = false)]
        public SortSortField? Field { get; set; }

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public AgentSortOrder? Order { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListRequestSort" /> class.
        /// </summary>
        /// <param name="evaluationOrder">evaluationOrder.</param>
        /// <param name="field">field.</param>
        /// <param name="order">order.</param>
        public ListRequestSort(long evaluationOrder = default(long), SortSortField? field = default(SortSortField?), AgentSortOrder? order = default(AgentSortOrder?))
        {
            this.EvaluationOrder = evaluationOrder;
            this.Field = field;
            this.Order = order;
        }

        /// <summary>
        /// Gets or Sets EvaluationOrder
        /// </summary>
        [DataMember(Name = "evaluationOrder", EmitDefaultValue = false)]
        public long EvaluationOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListRequestSort {\n");
            sb.Append("  EvaluationOrder: ").Append(EvaluationOrder).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
