/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using agent.Client;
using agent.Api;
// uncomment below to import models
//using agent.Model;

namespace agent.Test.Api
{
    /// <summary>
    ///  Class for testing AgentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AgentApiTests : IDisposable
    {
        private AgentApi instance;

        public AgentApiTests()
        {
            instance = new AgentApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AgentApi
            //Assert.IsType<AgentApi>(instance);
        }

        /// <summary>
        /// Test AgentCreateAgent
        /// </summary>
        [Fact]
        public void AgentCreateAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //AgentCreateAgentRequest body = null;
            //var response = instance.AgentCreateAgent(tenantId, body);
            //Assert.IsType<AgentAgentEntity>(response);
        }

        /// <summary>
        /// Test AgentGetAgent
        /// </summary>
        [Fact]
        public void AgentGetAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string id = null;
            //var response = instance.AgentGetAgent(tenantId, id);
            //Assert.IsType<AgentAgentEntity>(response);
        }

        /// <summary>
        /// Test AgentListAgents
        /// </summary>
        [Fact]
        public void AgentListAgentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //long pageSize = null;
            //AgentListAgentsRequest body = null;
            //var response = instance.AgentListAgents(tenantId, pageSize, body);
            //Assert.IsType<AgentListResponse>(response);
        }

        /// <summary>
        /// Test AgentUpdateAgent
        /// </summary>
        [Fact]
        public void AgentUpdateAgentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string id = null;
            //AgentUpdateAgentRequest body = null;
            //var response = instance.AgentUpdateAgent(tenantId, id, body);
            //Assert.IsType<AgentAgentEntity>(response);
        }
    }
}
