/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using agent.Model;
using agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace agent.Test.Model
{
    /// <summary>
    ///  Class for testing AgentCreateAgentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentCreateAgentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentCreateAgentRequest
        //private AgentCreateAgentRequest instance;

        public AgentCreateAgentRequestTests()
        {
            // TODO uncomment below to create an instance of AgentCreateAgentRequest
            //instance = new AgentCreateAgentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentCreateAgentRequest
        /// </summary>
        [Fact]
        public void AgentCreateAgentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentCreateAgentRequest
            //Assert.IsType<AgentCreateAgentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Fact]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }

        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Fact]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
    }
}
