/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using agent.Model;
using agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace agent.Test.Model
{
    /// <summary>
    ///  Class for testing AgentUpdateAgentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentUpdateAgentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentUpdateAgentRequest
        //private AgentUpdateAgentRequest instance;

        public AgentUpdateAgentRequestTests()
        {
            // TODO uncomment below to create an instance of AgentUpdateAgentRequest
            //instance = new AgentUpdateAgentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentUpdateAgentRequest
        /// </summary>
        [Fact]
        public void AgentUpdateAgentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentUpdateAgentRequest
            //Assert.IsType<AgentUpdateAgentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'PayloadMask'
        /// </summary>
        [Fact]
        public void PayloadMaskTest()
        {
            // TODO unit test for the property 'PayloadMask'
        }
    }
}
