/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using agent.Model;
using agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace agent.Test.Model
{
    /// <summary>
    ///  Class for testing AgentListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentListResponse
        //private AgentListResponse instance;

        public AgentListResponseTests()
        {
            // TODO uncomment below to create an instance of AgentListResponse
            //instance = new AgentListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentListResponse
        /// </summary>
        [Fact]
        public void AgentListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentListResponse
            //Assert.IsType<AgentListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Agents'
        /// </summary>
        [Fact]
        public void AgentsTest()
        {
            // TODO unit test for the property 'Agents'
        }

        /// <summary>
        /// Test the property 'PageToken'
        /// </summary>
        [Fact]
        public void PageTokenTest()
        {
            // TODO unit test for the property 'PageToken'
        }
    }
}
