/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using agent.Model;
using agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace agent.Test.Model
{
    /// <summary>
    ///  Class for testing AgentListAgentsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentListAgentsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentListAgentsRequest
        //private AgentListAgentsRequest instance;

        public AgentListAgentsRequestTests()
        {
            // TODO uncomment below to create an instance of AgentListAgentsRequest
            //instance = new AgentListAgentsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentListAgentsRequest
        /// </summary>
        [Fact]
        public void AgentListAgentsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentListAgentsRequest
            //Assert.IsType<AgentListAgentsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'PageToken'
        /// </summary>
        [Fact]
        public void PageTokenTest()
        {
            // TODO unit test for the property 'PageToken'
        }

        /// <summary>
        /// Test the property 'Sorts'
        /// </summary>
        [Fact]
        public void SortsTest()
        {
            // TODO unit test for the property 'Sorts'
        }

        /// <summary>
        /// Test the property 'FiltersMask'
        /// </summary>
        [Fact]
        public void FiltersMaskTest()
        {
            // TODO unit test for the property 'FiltersMask'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }
    }
}
