/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using agent.Model;
using agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace agent.Test.Model
{
    /// <summary>
    ///  Class for testing ListRequestFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListRequestFiltersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListRequestFilters
        //private ListRequestFilters instance;

        public ListRequestFiltersTests()
        {
            // TODO uncomment below to create an instance of ListRequestFilters
            //instance = new ListRequestFilters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListRequestFilters
        /// </summary>
        [Fact]
        public void ListRequestFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListRequestFilters
            //Assert.IsType<ListRequestFilters>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Fact]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
