/*
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using agent.Model;
using agent.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace agent.Test.Model
{
    /// <summary>
    ///  Class for testing ListRequestSort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListRequestSortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListRequestSort
        //private ListRequestSort instance;

        public ListRequestSortTests()
        {
            // TODO uncomment below to create an instance of ListRequestSort
            //instance = new ListRequestSort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListRequestSort
        /// </summary>
        [Fact]
        public void ListRequestSortInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListRequestSort
            //Assert.IsType<ListRequestSort>(instance);
        }

        /// <summary>
        /// Test the property 'EvaluationOrder'
        /// </summary>
        [Fact]
        public void EvaluationOrderTest()
        {
            // TODO unit test for the property 'EvaluationOrder'
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
    }
}
